spring:
  application:
    name: aidev
  ai:
    openai:
      api-key: <<>>>>
      chat:
        options:
          model: "gpt-4o"

client:
  xyz:
    url: https://xyz.ag3nts.org
  centrala:
    url: https://centrala.ag3nts.org
    api-key: <<>>

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

task: XyzAntiCaptcha

logging:
  level:
    org:
      eu:
        dabrowski:
          aidev: DEBUG

file:
  storage:
    location: <<>>

my-addresss: http://<<>>

qdrant:
  arvix:
    collection-name: arvix