spring:
  application:
    name: aidev
  ai:
    openai:
      api-key: <<>>>>
      chat:
        options:
          model: "gpt-4o"

client:
  xyz:
    url: https://xyz.ag3nts.org


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

task: XyzAntiCaptcha

logging:
  level:
    org:
      eu:
        dabrowski:
          aidev: DEBUG
